apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
  namespace: traefik
type: Opaque
data:
  # This is admin:password encoded with htpasswd
  # To generate: htpasswd -nb admin password
  users: YWRtaW46JGFwcjEkcnVjYTg0SHEkbWJqZE1aQkFHLktXbjZ2Zk4vU05LLwo=

